baseURL = 'https://icaps23.icaps-conference.org'
languageCode = 'en-us'
title = 'ICAPS 2023'
theme = 'mainroad'

[Params.logo]
  image = "img/icapslogo.png" # Logo image. Path relative to "static"
  title = "The 33rd International Conference" # Logo title, otherwise will use site title
  title2 = "on Automated Planning and Scheduling"
  subtitle = "Prague, July 8-13, 2023" # Logo subtitle

#[Params]
#   customCSS = ["css/bootstrap-table.css"]

[Params.style.vars]
     highlightColor = "#0081fe"

[menu]
# HOME
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url="/home"
    weight = 1
# DATES
  [[menu.main]]
    identifier = "dates"
    name = "Dates"
    url="/dates"
    weight = 2
# CALLS
  [[menu.main]]
    identifier = "calls"
    name = "Calls"
    weight = 3
  [[menu.main]]
    identifier = "main_track"
    name = "Main Track"
    url = "/calls/main_track"
    parent = "calls"
    weight = 1
  [[menu.main]]
    identifier = "application_track"
    name = "Application Track"
    url = "/calls/application_track"
    parent = "calls"
    weight = 2
  [[menu.main]]
    identifier = "learning_track"
    name = "Learning Track"
    url = "/calls/learning_track"
    parent = "calls"
    weight = 3
  [[menu.main]]
    identifier = "robotics_track"
    name = "Robotics Track"
    url = "/calls/robotics_track"
    parent = "calls"
    weight = 4
  [[menu.main]]
    identifier = "workshop_call"
    name = "Call for Workshop Proposals"
    url = "/calls/workshop_call"
    parent = "calls"
    weight = 5
  [[menu.main]]
    identifier = "tutorial_call"
    name = "Call for Tutorial Proposals"
    url = "/calls/tutorial_call"
    parent = "calls"
    weight = 6
  [[menu.main]]
    identifier = "partnership_call"
    name = "Call for Partnership"
    url = "/calls/partnership_call"
    parent = "calls"
    weight = 7
# COMPETITIONS
  [[menu.main]]
    identifier = "competitions"
    name = "Competitions"
    url="/competitions"
    weight = 4
# SUBMISSIONS
  [[menu.main]]
    identifier = "submissions"
    name = "Submissions"
    url="/submissions"
    weight = 4
# PROGRAM
  [[menu.main]]
    identifier = "program"
    name = "Program"
    weight = 5
  [[menu.main]]
    identifier = "program_overview"
    name = "Program Overview"
    url = "/program/overview"
    parent = "program"
    weight = 1
# COMMITTEES
  [[menu.main]]
    identifier = "committees"
    name = "Committees"
    weight = 6
  [[menu.main]]
    identifier = "organizers"
    name = "Organizers"
    url = "/committees/organizers"
    parent = "committees"
    weight = 1
#  [[menu.main]]
#    identifier = "program_committees"
#    name = "Program Committees"
#    url = "/committees/program_committees"
#    parent = "committees"
#    weight = 2
# CODE OF CONDUCT
  [[menu.main]]
    identifier = "code_of_conduct"
    name = "Code of Conduct"
    url = "/code_of_conduct"
    weight = 7
